-- 코드를 작성해주세요
SELECT DISTINCT
    DV.ID, 
    DV.EMAIL, 
    DV.FIRST_NAME, 
    DV.LAST_NAME
FROM DEVELOPERS AS DV
    JOIN SKILLCODES AS SK
    ON (SK.CODE & DV.SKILL_CODE) = SK.CODE
WHERE SK.NAME IN ('Python', 'C#')
ORDER BY DV.ID;